# Generated by Django 5.2.17 on 2026-09-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0007_document_options'),
        ('connections', '0002_connection_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('stripe_price_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=22)),
                ('currency', models.CharField(max_length=3)),
                ('precision', models.PositiveSmallIntegerField(default=2)),
                ('interval', models.CharField(choices=[('month', 'month'), ('year', 'year')], max_length=5)),
                ('trial_days', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('livemode', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['amount', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_positive_amount'), models.CheckConstraint(condition=models.Q(('precision__lte', 3)), name='billing_precision_range'), models.CheckConstraint(condition=models.Q(trial_days=0) | models.Q(trial_days__gte=2, trial_days__lte=90), name='billing_trial_range'), models.CheckConstraint(condition=models.Q(('interval__in', ['month', 'year'])), name='billing_interval')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('digest', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_digest', models.CharField(max_length=64)),
                ('stripe_session_id', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True, max_length=8192)),
                ('return_url', models.URLField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('trial_days', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'key_digest'), name='billing_checkout_idempotency'), models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'open'])), fields=('company',), name='billing_one_open_checkout'), models.UniqueConstraint(condition=models.Q(('stripe_session_id', ''), _negated=True), fields=('stripe_session_id',), name='billing_unique_checkout_session')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exempt', models.BooleanField(default=False)),
                ('livemode', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='none', max_length=24)),
                ('access_until', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('trial_used', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('stripe_customer_id', ''), _negated=True), fields=('stripe_customer_id',), name='billing_unique_customer'), models.UniqueConstraint(condition=models.Q(('stripe_subscription_id', ''), _negated=True), fields=('stripe_subscription_id',), name='billing_unique_subscription')],
            },
        ),
    ]
