# Generated by Django 5.2.17 on 2026-09-07 14:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('window_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('precision', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('document_language', models.CharField(choices=[('fr', 'fr'), ('en', 'en'), ('ar', 'ar'), ('de', 'de'), ('tr', 'tr')], default='fr', max_length=2)),
                ('locale', models.CharField(default='fr-FR', max_length=20)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('precision__lte', 4)), name='company_precision_range')],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('receivable', 'receivable'), ('revenue', 'revenue'), ('tax', 'tax'), ('bank', 'bank')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('accountant', 'accountant'), ('sales', 'sales'), ('viewer', 'viewer')], default='viewer', max_length=20)),
                ('language', models.CharField(choices=[('fr', 'fr'), ('en', 'en'), ('ar', 'ar'), ('de', 'de'), ('tr', 'tr')], default='fr', max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=80)),
                ('archived', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField(editable=False, null=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('invoice', 'invoice'), ('payment', 'payment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
        ),
        migrations.CreateModel(
            name='EntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=22)),
                ('credit', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=22)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('document_language', models.CharField(choices=[('fr', 'fr'), ('en', 'en'), ('ar', 'ar'), ('de', 'de'), ('tr', 'tr')], default='fr', max_length=2)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('validated', 'validated')], default='draft', max_length=12)),
                ('number', models.CharField(blank=True, default='', max_length=40)),
                ('precision', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('net', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=22)),
                ('tax', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=22)),
                ('total', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=22)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='erp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=30)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='erp.invoice'),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.journal'),
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=22)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='erp.invoice')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry', to='erp.payment'),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('closed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.period'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=22)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('archived', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=22)),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('net', models.DecimalField(decimal_places=6, max_digits=22)),
                ('tax', models.DecimalField(decimal_places=6, max_digits=22)),
                ('total', models.DecimalField(decimal_places=6, max_digits=22)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.product')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', '-created_at'], name='erp_auditev_company_aa44b9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='account_company_code'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'kind'), name='account_company_kind'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'archived', 'name'], name='erp_custome_company_32a08a_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='entry_line_one_positive_side'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'status', '-issue_date', '-id'], name='erp_invoice_company_f7eb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'customer'], name='erp_invoice_company_9fac5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'number'), name='invoice_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('net__gte', 0), ('tax__gte', 0), ('total__gte', 0)), name='invoice_nonnegative_amounts'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('issue_date'))), name='invoice_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('net'), '+', models.F('tax')))), name='invoice_total_sum'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('precision__isnull', False), ('status', 'validated'), ('validated_at__isnull', False), models.Q(('number', ''), _negated=True), models.Q(('currency', ''), _negated=True)), _connector='OR'), name='invoice_validation_state'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='idempotency_company_key'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='journal_company_code'),
        ),
        migrations.AddConstraint(
            model_name='numbersequence',
            constraint=models.UniqueConstraint(fields=('company', 'year'), name='sequence_company_year'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_positive_amount'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['company', 'start', 'end'], name='erp_period_company_885b03_idx'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='period_dates_order'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['company', 'period', 'date'], name='erp_entry_company_2bf1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['company', 'journal', 'date'], name='erp_entry_company_688c4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'invoice')), fields=('invoice',), name='single_invoice_entry'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'archived', 'name'], name='erp_product_company_c6d95e_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'reference'), name='product_company_reference'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='product_nonnegative_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='product_tax_range'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('net__gte', 0), ('quantity__gt', 0), ('tax__gte', 0), ('unit_price__gte', 0)), name='invoice_line_amounts'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='invoice_line_tax_range'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('net'), '+', models.F('tax')))), name='invoice_line_total_sum'),
        ),
    ]
