# Generated by Django 5.2.17 on 2026-09-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_financial_guards'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', '-issue_date', '-id'], name='erp_invoice_company_741397_idx'),
        ),
    ]
