# Generated by Django 5.2.17 on 2026-09-07 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_invoice_erp_invoice_company_741397_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='locale',
            field=models.CharField(default='fr-FR', max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2,3}(?:-[A-Za-z]{4})?(?:-(?:[A-Za-z]{2}|[0-9]{3}))?$', message='Paramètres régionaux invalides.')]),
        ),
    ]
