# Generated by Django 5.2.17 on 2026-09-10 16:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_catalog_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=22)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='bic',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_discount_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7),
        ),
        migrations.AddField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='customer',
            name='latin_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms_days',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_address',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='latin_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('company', 'reference'), name='customer_company_reference'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('payment_terms_days__lte', 365)), name='customer_payment_days'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('default_discount_rate__gte', 0), ('default_discount_rate__lte', 100)), name='customer_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit__isnull', True), ('credit_limit__gte', 0), _connector='OR'), name='customer_credit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('weight__isnull', True), ('weight__gte', 0), _connector='OR'), name='product_weight_nonnegative'),
        ),
        migrations.AddField(
            model_name='customerprice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company'),
        ),
        migrations.AddField(
            model_name='customerprice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='erp.customer'),
        ),
        migrations.AddField(
            model_name='customerprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_prices', to='erp.product'),
        ),
        migrations.AddConstraint(
            model_name='customerprice',
            constraint=models.UniqueConstraint(fields=('company', 'customer', 'product'), name='customer_price_unique'),
        ),
        migrations.AddConstraint(
            model_name='customerprice',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='customer_price_nonnegative'),
        ),
    ]
