# Generated by Django 5.2.17 on 2026-09-10 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0007_document_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('currency', models.CharField(max_length=3)),
                ('archived', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('website', 'website'), ('payments', 'payments'), ('bank', 'bank'), ('other', 'other')], max_length=20)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=24)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keys', to='connections.integration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=22)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='connections.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.invoice')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.payment')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'account', '-date', '-id'], name='connections_company_6c1d92_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'account', 'external_id'), name='bank_transaction_unique_id'), models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='bank_transaction_nonzero'), models.CheckConstraint(condition=models.Q(models.Q(('invoice__isnull', True), ('payment__isnull', True), ('reconciled_at__isnull', True)), models.Q(('invoice__isnull', False), ('payment__isnull', False), ('reconciled_at__isnull', False)), _connector='OR'), name='bank_transaction_reconciled_state')],
            },
        ),
        migrations.CreateModel(
            name='ExternalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=22)),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connections.integration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'integration', 'external_id'), name='external_transaction_unique_id'), models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='external_transaction_nonzero')],
            },
        ),
        migrations.CreateModel(
            name='ExternalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=80)),
                ('fingerprint', models.CharField(max_length=64)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connections.integration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'integration', 'key'), name='external_request_unique_key')],
            },
        ),
    ]
