<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { api, errorCode } from '../api'
import { canPost, session } from '../session'
import { useList } from '../useList'
import { date, money } from '../format'
import type { AuditEvent, Entry, Journal, Page, Period, TrialBalance } from '../types'
import ErrorNotice from '../components/ErrorNotice.vue'
import Pagination from '../components/Pagination.vue'
const { t, te } = useI18n()
const tab = ref('journal'); const period = ref(''); const journal = ref(''); const periods = ref<Period[]>([]); const journals = ref<Journal[]>([])
const filters = computed(() => ({ period: period.value, journal: journal.value, ordering: '-date' }))
const { items, count, page, loading, error, reload } = useList<Entry>(() => 'entries/', filters)
const balance = ref<TrialBalance | null>(null); const balanceLoading = ref(false); const extraError = ref(''); const selected = ref<Entry | null>(null)
const audit = ref<Page<AuditEvent>>({ count: 0, next: null, previous: null, results: [] }); const auditPage = ref(1); const auditLoading = ref(false)
function price(value: string) { const company = session.company!; return money(value, company.currency, company.locale, company.precision) }
onMounted(async () => { try { const responses = await Promise.all([api<Page<Period>>('periods/?page_size=50&ordering=-start'), api<Page<Journal>>('journals/?page_size=50')]); periods.value = responses[0].results; journals.value = responses[1].results } catch (cause) { extraError.value = errorCode(cause) } })
let balanceRequest = 0
async function loadBalance() { const request = ++balanceRequest; balance.value = null; if (!period.value) return; balanceLoading.value = true; extraError.value = ''; try { const result = await api<TrialBalance>(`trial-balance/?period=${period.value}`); if (request === balanceRequest) balance.value = result } catch (cause) { if (request === balanceRequest) extraError.value = errorCode(cause) } finally { if (request === balanceRequest) balanceLoading.value = false } }
async function loadAudit() { auditLoading.value = true; extraError.value = ''; try { audit.value = await api<Page<AuditEvent>>(`audit/?page=${auditPage.value}&page_size=50`) } catch (cause) { extraError.value = errorCode(cause) } finally { auditLoading.value = false } }
watch([tab, period], () => { if (tab.value === 'trialBalance') void loadBalance(); if (tab.value === 'audit') void loadAudit(); selected.value = null })
watch(auditPage, () => { void loadAudit() })
async function detail(item: Entry) { extraError.value = ''; try { selected.value = item.lines ? item : await api<Entry>(`entries/${item.id}/`) } catch (cause) { extraError.value = errorCode(cause) } }
</script>
<template><div class="page-heading"><div><span class="eyebrow">{{ t('financeSection') }}</span><h1>{{ t('accounting') }}</h1><p>{{ t('accountingIntro') }}</p></div></div><section class="card"><div class="table-toolbar"><div class="segmented" role="group" :aria-label="t('accounting')"><button v-for="value in (canPost ? ['journal', 'trialBalance', 'audit'] : ['journal', 'trialBalance'])" :key="value" :class="{ selected: tab === value }" :aria-pressed="tab === value" @click="tab = value">{{ t(value) }}</button></div><div v-if="tab !== 'audit'" class="toolbar-filters"><select v-model="period" :aria-label="t('period')"><option value="">{{ t('allPeriods') }}</option><option v-for="item in periods" :key="item.id" :value="String(item.id)">{{ item.name }}</option></select><select v-if="tab === 'journal'" v-model="journal" :aria-label="t('journal')"><option value="">{{ t('allJournals') }}</option><option v-for="item in journals" :key="item.id" :value="String(item.id)">{{ item.code }} · {{ item.name }}</option></select></div></div><ErrorNotice :code="extraError" />
  <template v-if="tab === 'journal'"><ErrorNotice :code="error" /><div v-if="loading" class="loading-state" role="status">{{ t('loading') }}</div><div v-else-if="!items.length" class="empty-state"><h2>{{ t('noResults') }}</h2><button v-if="error" class="button subtle" @click="reload">{{ t('retry') }}</button></div><div v-else class="table-scroll"><table><thead><tr><th>{{ t('date') }}</th><th>{{ t('journal') }}</th><th>{{ t('reference') }}</th><th class="numeric">{{ t('debit') }}</th><th class="numeric">{{ t('credit') }}</th><th>{{ t('actions') }}</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><bdi>{{ date(item.date, session.company!.locale) }}</bdi></td><td><span class="badge neutral"><bdi>{{ item.journal_code }}</bdi></span></td><td><RouterLink class="table-link" :to="`/invoices/${item.invoice}`"><bdi>{{ item.reference }}</bdi></RouterLink></td><td class="numeric"><bdi>{{ price(item.total_debit) }}</bdi></td><td class="numeric"><bdi>{{ price(item.total_credit) }}</bdi></td><td><button class="text-button" @click="detail(item)">{{ t('viewEntry') }}</button></td></tr></tbody></table></div><Pagination :page="page" :count="count" :busy="loading" @change="page = $event" /></template>
  <template v-else-if="tab === 'trialBalance'"><div v-if="balanceLoading" class="loading-state" role="status">{{ t('loading') }}</div><div v-else-if="!balance" class="empty-state"><h2>{{ t('trialBalance') }}</h2><p>{{ t('balanceHelp') }}</p></div><div v-else class="table-scroll"><table><thead><tr><th>{{ t('account') }}</th><th>{{ t('name') }}</th><th class="numeric">{{ t('debit') }}</th><th class="numeric">{{ t('credit') }}</th><th class="numeric">{{ t('movementBalance') }}</th></tr></thead><tbody><tr v-for="item in balance.accounts" :key="item.code"><td><bdi>{{ item.code }}</bdi></td><td><bdi>{{ item.name }}</bdi></td><td class="numeric"><bdi>{{ price(item.debit) }}</bdi></td><td class="numeric"><bdi>{{ price(item.credit) }}</bdi></td><td class="numeric"><bdi>{{ price(item.balance) }}</bdi></td></tr></tbody><tfoot><tr><th colspan="2">{{ t('trialBalance') }}</th><td class="numeric"><bdi>{{ price(balance.total_debit) }}</bdi></td><td class="numeric"><bdi>{{ price(balance.total_credit) }}</bdi></td><td></td></tr></tfoot></table></div></template>
  <template v-else><div v-if="auditLoading" class="loading-state" role="status">{{ t('loading') }}</div><div v-else-if="!audit.results.length" class="empty-state"><h2>{{ t('noResults') }}</h2></div><div v-else class="table-scroll"><table><thead><tr><th>{{ t('date') }}</th><th>{{ t('actor') }}</th><th>{{ t('action') }}</th><th>{{ t('object') }}</th></tr></thead><tbody><tr v-for="item in audit.results" :key="item.id"><td><bdi>{{ date(item.created_at, session.company!.locale) }}</bdi></td><td><bdi>{{ item.actor_name }}</bdi></td><td><bdi>{{ te('audit_' + item.action.replaceAll('.', '_')) ? t('audit_' + item.action.replaceAll('.', '_')) : item.action }}</bdi></td><td><bdi>{{ item.object_type }} #{{ item.object_id }}</bdi></td></tr></tbody></table></div><Pagination :page="auditPage" :count="audit.count" :busy="auditLoading" @change="auditPage = $event" /></template>
  </section><section v-if="selected && tab === 'journal'" class="card section-card"><div class="section-heading"><h2><bdi>{{ selected.reference }}</bdi></h2><button class="button subtle small" @click="selected = null">{{ t('close') }}</button></div><div class="table-scroll"><table><thead><tr><th>{{ t('account') }}</th><th class="numeric">{{ t('debit') }}</th><th class="numeric">{{ t('credit') }}</th></tr></thead><tbody><tr v-for="(line, index) in selected.lines" :key="index"><td><bdi>{{ line.account_code }}</bdi></td><td class="numeric"><bdi>{{ price(line.debit) }}</bdi></td><td class="numeric"><bdi>{{ price(line.credit) }}</bdi></td></tr></tbody></table></div></section></template>
