<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { api, errorCode, write } from '../api'
import { date, decimal, isZero } from '../format'
import { session } from '../session'
import { listQuery, useList } from '../useList'
import type { BankAccount, BankTransaction, CsvPreview, ExternalTransaction } from '../connectionTypes'
import type { Invoice } from '../types'
import ErrorNotice from '../components/ErrorNotice.vue'
import Pagination from '../components/Pagination.vue'
const { t } = useI18n()
const accounts = useList<BankAccount>(() => 'bank-accounts/', ref({}))
const selectedAccount = ref<BankAccount | null>(null); const editAccount = ref<BankAccount | null>(null)
const form = reactive({ name: '', bank_name: '', iban: '', bic: '', currency: session.company!.currency, archived: false })
const filters = reactive({ reconciled: '', date_from: '', date_to: '' })
const transactionFilters = computed(() => ({ ...filters, account: selectedAccount.value ? String(selectedAccount.value.id) : '' }))
const transactions = useList<BankTransaction>(() => 'bank-transactions/', transactionFilters)
const external = useList<ExternalTransaction>(() => 'external-transactions/', ref({}))
const invoices = useList<Invoice>(() => 'invoices/', ref({ status: 'validated' }))
const summary = ref<{ count: number; amount: string; currency: string } | null>(null)
const error = ref(''); const busy = ref(false); const success = ref(''); const csv = ref(''); const preview = ref<CsvPreview | null>(null)
const reconcile = ref<BankTransaction | null>(null); const chosenInvoice = ref<Invoice | null>(null); const confirmed = ref(false)
const tab = ref('bank'); let summaryVersion = 0
async function refreshSummary() { const version = ++summaryVersion; try { const query = listQuery(1, transactions.search.value, transactionFilters.value); const result = await api<{ count: number; amount: string; currency: string }>(`bank-transactions/summary/?${query}`); if (version === summaryVersion) summary.value = result } catch (cause) { if (version === summaryVersion) error.value = errorCode(cause) } }
watch([transactionFilters, transactions.search], () => { void refreshSummary() }, { immediate: true, deep: true })
watch([csv, selectedAccount], () => { preview.value = null; success.value = '' })
async function mutation(operation: () => Promise<void>) { if (busy.value) return; busy.value = true; error.value = ''; success.value = ''; try { await operation() } catch (cause) { error.value = errorCode(cause) } finally { busy.value = false } }
function edit(item?: BankAccount) { editAccount.value = item ?? null; Object.assign(form, item ?? { name: '', bank_name: '', iban: '', bic: '', currency: session.company!.currency, archived: false }) }
async function saveAccount() { await mutation(async () => { const result = await write<BankAccount>(editAccount.value ? `bank-accounts/${editAccount.value.id}/` : 'bank-accounts/', { name: form.name, bank_name: form.bank_name, iban: form.iban, bic: form.bic, currency: form.currency, archived: form.archived }, editAccount.value ? 'PATCH' : 'POST'); selectedAccount.value = result; edit(); await accounts.reload(); success.value = 'saved' }) }
async function readFile(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; if (file.size > 250000) { error.value = 'invalid_input'; return } try { csv.value = new window.TextDecoder('utf-8', { fatal: true }).decode(await file.arrayBuffer()); error.value = '' } catch { error.value = 'invalid_input' } }
async function importCsv(confirm = false) { if (!selectedAccount.value) return; const accountId = selectedAccount.value.id; const content = csv.value; const digest = preview.value?.preview_digest; await mutation(async () => { const result = await write<CsvPreview>(`bank-accounts/${accountId}/import/`, { csv: content, confirm, ...(confirm ? { preview_digest: digest } : {}) }); if (selectedAccount.value?.id === accountId && csv.value === content) preview.value = result; if (confirm) { await transactions.reload(); await refreshSummary(); success.value = 'bankImported' } }) }
function startReconcile(item: BankTransaction) { reconcile.value = item; chosenInvoice.value = null; confirmed.value = false; invoices.search.value = item.reference }
async function applyReconcile() { if (!reconcile.value || !chosenInvoice.value || !confirmed.value) return; const transactionId = reconcile.value.id; const invoiceId = chosenInvoice.value.id; await mutation(async () => { await write(`bank-transactions/${transactionId}/reconcile/`, { invoice: invoiceId, confirm: true }); reconcile.value = null; chosenInvoice.value = null; await transactions.reload(); await invoices.reload(); await refreshSummary(); success.value = 'bankReconciled' }) }
function positive(value: string) { return !value.startsWith('-') && !isZero(value) }
</script>
<template>
  <div class="page-heading"><div><span class="eyebrow">{{ t('connectionWorkspace') }}</span><h1>{{ t('banking') }}</h1><p>{{ t('bankingIntro') }}</p></div></div>
  <p class="notice" role="note">{{ t('bankManualNotice') }}</p><ErrorNotice :code="error || accounts.error.value || transactions.error.value || external.error.value" /><p v-if="success" class="notice success" role="status">{{ t(success) }}</p>
  <div class="segmented"><button :class="{ selected: tab === 'bank' }" @click="tab = 'bank'">{{ t('bankTransactions') }}</button><button :class="{ selected: tab === 'external' }" @click="tab = 'external'">{{ t('externalTransactions') }}</button></div>
  <template v-if="tab === 'bank'">
    <section class="card section-card"><h2>{{ t(editAccount ? 'bankEditAccount' : 'bankNewAccount') }}</h2><form @submit.prevent="saveAccount"><fieldset :disabled="busy"><div class="form-grid"><label class="field"><span>{{ t('name') }} *</span><input v-model="form.name" required maxlength="150" /></label><label class="field"><span>{{ t('bankName') }}</span><input v-model="form.bank_name" maxlength="150" /></label><label class="field"><span>{{ t('bankIban') }}</span><input v-model="form.iban" maxlength="42" dir="ltr" /></label><label class="field"><span>{{ t('bankBic') }}</span><input v-model="form.bic" maxlength="11" dir="ltr" /></label><label class="field"><span>{{ t('currency') }}</span><input :value="form.currency" readonly /></label><label class="bank-check"><input v-model="form.archived" type="checkbox" />{{ t('archived') }}</label></div></fieldset><div class="form-actions"><button class="button primary" :disabled="busy">{{ t('save') }}</button><button v-if="editAccount" type="button" class="button subtle" @click="edit()">{{ t('cancel') }}</button></div></form></section>
    <section class="card section-card"><h2>{{ t('bankAccounts') }}</h2><label class="field"><span>{{ t('search') }}</span><input v-model="accounts.search.value" type="search" /></label><div class="bank-account-list"><button class="button subtle" :aria-pressed="!selectedAccount" @click="selectedAccount = null">{{ t('bankAllAccounts') }}</button><div v-for="item in accounts.items.value" :key="item.id" class="bank-account"><button class="button" :class="selectedAccount?.id === item.id ? 'primary' : 'subtle'" :aria-pressed="selectedAccount?.id === item.id" @click="selectedAccount = item">{{ item.name }} · {{ item.currency }}{{ item.archived ? ` · ${t('archived')}` : '' }}</button><button class="text-button" @click="edit(item)">{{ t('edit') }}</button></div></div><Pagination :page="accounts.page.value" :count="accounts.count.value" :busy="accounts.loading.value" @change="accounts.page.value = $event" /></section>
    <section v-if="selectedAccount && !selectedAccount.archived" class="card section-card"><h2>{{ t('bankImportCsv') }} — {{ selectedAccount.name }}</h2><p>{{ t('bankCsvHelp') }}</p><pre dir="ltr" class="bank-code">external_id,date,amount,description,reference
TX-001,2026-09-10,100.00,Payment,INV-2026-000001</pre><label class="field"><span>{{ t('bankCsvFile') }}</span><input type="file" accept=".csv,text/csv" :disabled="busy" @change="readFile" /></label><label class="field"><span>{{ t('bankCsvContent') }}</span><textarea v-model="csv" rows="5" maxlength="250000" dir="ltr" :disabled="busy" /></label><div class="form-actions"><button class="button primary" :disabled="busy || !csv" @click="importCsv(false)">{{ t('bankPreview') }}</button></div>
      <div v-if="preview" class="bank-preview"><p>{{ t('bankPreviewSummary', { count: preview.count, duplicates: preview.duplicates, total: decimal(preview.total, session.company!.locale) }) }}</p><div class="table-scroll bank-preview-scroll"><table><thead><tr><th>{{ t('reference') }}</th><th>{{ t('date') }}</th><th>{{ t('amount') }}</th><th>{{ t('description') }}</th></tr></thead><tbody><tr v-for="row in preview.rows" :key="row.external_id"><td>{{ row.external_id }}</td><td>{{ row.date }}</td><td dir="ltr">{{ row.amount }}</td><td>{{ row.description }}</td></tr></tbody></table></div><div class="form-actions"><button v-if="!preview.confirmed" class="button primary" :disabled="busy" @click="importCsv(true)">{{ t('bankConfirmImport') }}</button><p v-else role="status">{{ t('bankImportResult', { count: preview.created }) }}</p></div></div>
    </section>
    <section class="card section-card"><h2>{{ t('bankTransactions') }}</h2><div class="form-grid"><label class="field"><span>{{ t('search') }}</span><input v-model="transactions.search.value" type="search" /></label><label class="field"><span>{{ t('status') }}</span><select v-model="filters.reconciled"><option value="">{{ t('bankAllStates') }}</option><option value="false">{{ t('bankUnreconciled') }}</option><option value="true">{{ t('bankReconciled') }}</option></select></label><label class="field"><span>{{ t('start') }}</span><input v-model="filters.date_from" type="date" /></label><label class="field"><span>{{ t('end') }}</span><input v-model="filters.date_to" type="date" /></label></div><p v-if="summary" class="bank-summary">{{ t('bankSummary', { count: summary.count, amount: decimal(summary.amount, session.company!.locale), currency: summary.currency }) }}</p><p v-if="transactions.loading.value" role="status">{{ t('loading') }}</p><div class="table-scroll"><table><thead><tr><th>{{ t('date') }}</th><th>{{ t('bankAccount') }}</th><th>{{ t('reference') }}</th><th>{{ t('description') }}</th><th>{{ t('amount') }}</th><th>{{ t('actions') }}</th></tr></thead><tbody><tr v-for="item in transactions.items.value" :key="item.id"><td>{{ date(item.date, session.company!.locale) }}</td><td>{{ item.account_name }}</td><td>{{ item.reference || item.external_id }}</td><td>{{ item.description }}</td><td dir="ltr">{{ decimal(item.amount, session.company!.locale) }}</td><td><RouterLink v-if="item.invoice" :to="`/invoices/${item.invoice}`">{{ item.invoice_number }}</RouterLink><button v-else-if="positive(item.amount)" class="text-button" @click="startReconcile(item)">{{ t('bankReconcile') }}</button><span v-else>{{ t('bankUnreconciled') }}</span></td></tr></tbody></table></div><p v-if="!transactions.loading.value && !transactions.items.value.length">{{ t('noResults') }}</p><Pagination :page="transactions.page.value" :count="transactions.count.value" :busy="transactions.loading.value" @change="transactions.page.value = $event" /></section>
    <section v-if="reconcile" class="card section-card bank-confirm"><h2>{{ t('bankReconcile') }}</h2><p>{{ t('bankReconcileHelp') }}</p><p>{{ reconcile.reference || reconcile.external_id }} · <bdi>{{ decimal(reconcile.amount, session.company!.locale) }} {{ session.company!.currency }}</bdi></p><label class="field"><span>{{ t('bankFindInvoice') }}</span><input v-model="invoices.search.value" type="search" /></label><ErrorNotice :code="invoices.error.value" /><div class="bank-invoices"><button v-for="invoice in invoices.items.value.filter(item => !isZero(item.balance))" :key="invoice.id" class="button subtle" :aria-pressed="chosenInvoice?.id === invoice.id" @click="chosenInvoice = invoice">{{ invoice.number }} · {{ invoice.customer_name }} · {{ decimal(invoice.balance, session.company!.locale) }} {{ session.company!.currency }}{{ chosenInvoice?.id === invoice.id ? ' ✓' : '' }}</button></div><Pagination :page="invoices.page.value" :count="invoices.count.value" :busy="invoices.loading.value" @change="invoices.page.value = $event" /><label class="bank-check"><input v-model="confirmed" type="checkbox" />{{ t('bankReconcileConfirm') }}</label><div class="form-actions"><button class="button primary" :disabled="busy || !chosenInvoice || !confirmed" @click="applyReconcile">{{ t('bankRecordPayment') }}</button><button class="button subtle" :disabled="busy" @click="reconcile = null">{{ t('cancel') }}</button></div></section>
  </template>
  <section v-else class="card section-card"><h2>{{ t('externalTransactions') }}</h2><p>{{ t('externalReceivedHelp') }}</p><label class="field"><span>{{ t('search') }}</span><input v-model="external.search.value" type="search" /></label><div class="table-scroll"><table><thead><tr><th>{{ t('date') }}</th><th>{{ t('integrations') }}</th><th>{{ t('reference') }}</th><th>{{ t('amount') }}</th><th>{{ t('status') }}</th></tr></thead><tbody><tr v-for="item in external.items.value" :key="item.id"><td>{{ date(item.date, session.company!.locale) }}</td><td>{{ item.integration_name }}</td><td>{{ item.reference || item.external_id }}</td><td>{{ decimal(item.amount, session.company!.locale) }} {{ item.currency }}</td><td>{{ t('externalReceived') }}</td></tr></tbody></table></div><p v-if="!external.items.value.length">{{ t('noResults') }}</p><Pagination :page="external.page.value" :count="external.count.value" :busy="external.loading.value" @change="external.page.value = $event" /></section>
</template>
<style scoped>
.bank-check, .bank-account { display: flex; align-items: center; gap: 10px; }
.bank-check input { inline-size: auto; }
.bank-account-list, .bank-invoices { display: flex; flex-wrap: wrap; gap: 12px; margin-block: 16px; }
.bank-code { white-space: pre-wrap; overflow-wrap: anywhere; padding: 12px; background: #edf5ff; font-size: 11px; }
.bank-preview-scroll { max-block-size: 350px; }
.bank-preview { margin-block-start: 20px; }
.bank-summary { font-weight: 600; }
.bank-confirm { border: 2px solid var(--primary); }
</style>
