<script setup lang="ts">
import { defineAsyncComponent, reactive, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { api, errorCode, write } from '../api'
import { isAdmin, session } from '../session'
import { date, today } from '../format'
import { languages, type Company, type Language, type Page, type Period, type Role, type User } from '../types'
import ErrorNotice from '../components/ErrorNotice.vue'
import Icon from '../components/Icon.vue'
import Pagination from '../components/Pagination.vue'
const CatalogSettings = defineAsyncComponent(() => import('../components/CatalogSettings.vue'))
const { t } = useI18n(); const tab = ref('company'); const busy = ref(false); const loading = ref(false); const error = ref(''); const success = ref(false)
const company = reactive({ ...session.company! }); const periods = ref<Page<Period>>({ count: 0, next: null, previous: null, results: [] }); const users = ref<Page<User>>({ count: 0, next: null, previous: null, results: [] })
const page = ref(1); const showForm = ref(false)
const periodForm = reactive({ name: '', start: today(), end: today() })
const userForm = reactive({ username: '', password: '', role: 'viewer' as Role, language: 'fr' as Language })
const roles: Role[] = ['admin', 'accountant', 'sales', 'viewer']
async function load() { if (!isAdmin.value || !['periods', 'users'].includes(tab.value)) return; loading.value = true; error.value = ''; try { if (tab.value === 'periods') periods.value = await api<Page<Period>>(`periods/?page=${page.value}&page_size=50&ordering=-start`); else users.value = await api<Page<User>>(`users/?page=${page.value}&page_size=50`) } catch (cause) { error.value = errorCode(cause) } finally { loading.value = false } }
watch(tab, () => { showForm.value = false; success.value = false; if (page.value !== 1) page.value = 1; else void load() })
watch(page, () => { void load() })
async function mutation(action: () => Promise<void>) { if (busy.value) return; busy.value = true; error.value = ''; success.value = false; try { await action(); success.value = true } catch (cause) { error.value = errorCode(cause) } finally { busy.value = false } }
async function saveCompany() { await mutation(async () => { const { name, address, email, currency, precision, document_language, locale } = company; session.company = await write<Company>('company/', { name, address, email, currency, precision: Number(precision), document_language, locale }, 'PATCH'); Object.assign(company, session.company) }) }
async function createPeriod() { await mutation(async () => { await write('periods/', { ...periodForm, closed: false }); showForm.value = false; periodForm.name = ''; await load() }) }
async function togglePeriod(item: Period) { await mutation(async () => { await write(`periods/${item.id}/`, { closed: !item.closed }, 'PATCH'); await load() }) }
async function createUser() { await mutation(async () => { await write('users/', { ...userForm, is_active: true }); userForm.password = ''; userForm.username = ''; showForm.value = false; await load() }) }
async function changeUser(item: User, values: Partial<User>) { await mutation(async () => { await write(`users/${item.id}/`, values, 'PATCH'); if (item.id === session.user?.id) session.user = await api<User>('auth/me/'); await load() }) }
function changeRole(item: User, event: Event) { void changeUser(item, { role: (event.target as HTMLSelectElement).value as Role }); (event.target as HTMLSelectElement).value = item.role }
</script>
<template><div class="page-heading"><div><span class="eyebrow">{{ t('financeSection') }}</span><h1>{{ t('settings') }}</h1><p>{{ t('settingsIntro') }}</p></div></div><div class="settings-tabs segmented" role="group" :aria-label="t('settings')"><button v-for="value in (isAdmin ? ['company', 'periods', 'users', 'catalog'] : ['company'])" :key="value" :class="{ selected: tab === value }" :aria-pressed="tab === value" @click="tab = value">{{ t(value) }}</button></div><ErrorNotice :code="error" /><div v-if="success" class="notice success" role="status">{{ t('saved') }}</div>
  <section v-if="tab === 'company'" class="card section-card settings-company"><h2>{{ t('company') }}</h2><p class="form-help">{{ t('localeHelp') }}</p><form @submit.prevent="saveCompany"><fieldset :disabled="busy || !isAdmin"><div class="form-grid"><label class="field"><span>{{ t('name') }} *</span><input v-model="company.name" name="company_name" required maxlength="200" /></label><label class="field"><span>{{ t('email') }}</span><input v-model="company.email" type="email" dir="ltr" /></label><label class="field full"><span>{{ t('address') }}</span><textarea v-model="company.address" rows="2" /></label><label class="field"><span>{{ t('currency') }} *</span><input v-model="company.currency" required pattern="[A-Z]{3}" maxlength="3" dir="ltr" /></label><label class="field"><span>{{ t('precision') }} *</span><input v-model="company.precision" type="number" required min="0" max="4" /></label><label class="field"><span>{{ t('documentLanguage') }}</span><select v-model="company.document_language"><option v-for="language in languages" :key="language" :value="language">{{ t(`lang_${language}`) }}</option></select></label><label class="field"><span>{{ t('locale') }}</span><select v-model="company.locale"><option v-for="region in ['fr-FR', 'en-GB', 'en-US', 'ar', 'de-DE', 'tr-TR']" :key="region" :value="region">{{ region }}</option><option v-if="!['fr-FR', 'en-GB', 'en-US', 'ar', 'de-DE', 'tr-TR'].includes(company.locale)" :value="company.locale">{{ company.locale }}</option></select></label></div></fieldset><div v-if="isAdmin" class="form-actions"><button class="button primary" type="submit" :disabled="busy">{{ t(busy ? 'saving' : 'save') }}</button></div></form></section>
  <CatalogSettings v-else-if="isAdmin && tab === 'catalog'" />
  <template v-else-if="isAdmin"><div class="section-heading"><h2>{{ t(tab) }}</h2><button class="button primary" @click="showForm = !showForm"><Icon name="plus" />{{ t(tab === 'periods' ? 'newPeriod' : 'newUser') }}</button></div><section v-if="showForm" class="card section-card"><form v-if="tab === 'periods'" @submit.prevent="createPeriod"><fieldset :disabled="busy"><div class="form-grid three"><label class="field"><span>{{ t('name') }} *</span><input v-model="periodForm.name" required /></label><label class="field"><span>{{ t('start') }} *</span><input v-model="periodForm.start" type="date" required /></label><label class="field"><span>{{ t('end') }} *</span><input v-model="periodForm.end" :min="periodForm.start" type="date" required /></label></div></fieldset><div class="form-actions"><button class="button primary" type="submit" :disabled="busy">{{ t(busy ? 'saving' : 'save') }}</button></div></form><form v-else @submit.prevent="createUser"><fieldset :disabled="busy"><div class="form-grid"><label class="field"><span>{{ t('username') }} *</span><input v-model="userForm.username" required maxlength="150" autocomplete="off" /></label><label class="field"><span>{{ t('password') }} *</span><input v-model="userForm.password" type="password" required minlength="12" autocomplete="new-password" /></label><label class="field"><span>{{ t('role') }}</span><select v-model="userForm.role"><option v-for="role in roles" :key="role" :value="role">{{ t(`role_${role}`) }}</option></select></label><label class="field"><span>{{ t('language') }}</span><select v-model="userForm.language"><option v-for="language in languages" :key="language" :value="language">{{ t(`lang_${language}`) }}</option></select></label></div></fieldset><div class="form-actions"><button class="button primary" type="submit" :disabled="busy">{{ t(busy ? 'saving' : 'save') }}</button></div></form></section>
  <section class="card"><div v-if="loading" class="loading-state" role="status">{{ t('loading') }}</div><template v-else-if="tab === 'periods'"><div v-if="!periods.results.length" class="empty-state"><h2>{{ t('noResults') }}</h2></div><div v-else class="table-scroll"><table><thead><tr><th>{{ t('name') }}</th><th>{{ t('start') }}</th><th>{{ t('end') }}</th><th>{{ t('status') }}</th><th>{{ t('actions') }}</th></tr></thead><tbody><tr v-for="item in periods.results" :key="item.id"><td class="strong"><bdi>{{ item.name }}</bdi></td><td><bdi>{{ date(item.start, company.locale) }}</bdi></td><td><bdi>{{ date(item.end, company.locale) }}</bdi></td><td><span class="badge" :class="item.closed ? 'neutral' : 'green'">{{ t(item.closed ? 'closed' : 'opened') }}</span></td><td><button class="text-button" :disabled="busy" @click="togglePeriod(item)">{{ t(item.closed ? 'reopenPeriod' : 'closePeriod') }}</button></td></tr></tbody></table></div><Pagination :page="page" :count="periods.count" @change="page = $event" /></template><template v-else><div v-if="!users.results.length" class="empty-state"><h2>{{ t('noResults') }}</h2></div><div v-else class="table-scroll"><table><thead><tr><th>{{ t('username') }}</th><th>{{ t('role') }}</th><th>{{ t('status') }}</th><th>{{ t('actions') }}</th></tr></thead><tbody><tr v-for="item in users.results" :key="item.id"><td class="strong"><bdi>{{ item.username }}</bdi></td><td><select :value="item.role" :aria-label="`${t('role')} ${item.username}`" :disabled="busy" @change="changeRole(item, $event)"><option v-for="role in roles" :key="role" :value="role">{{ t(`role_${role}`) }}</option></select></td><td><span class="badge" :class="item.is_active ? 'green' : 'neutral'">{{ t(item.is_active ? 'enabled' : 'disabled') }}</span></td><td><button class="text-button" :disabled="busy" @click="changeUser(item, { is_active: !item.is_active })">{{ t(item.is_active ? 'disable' : 'enable') }}</button></td></tr></tbody></table></div><Pagination :page="page" :count="users.count" @change="page = $event" /></template></section><p class="page-note">{{ t('accessHelp') }}</p></template></template>
